// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616034137_AlterMedia")]
    partial class AlterMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ece85-3268-7743-a256-61730dcbc7a0"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3148), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019ece85-30ad-7412-88c2-a81a44c998fc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3100), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7a6e-9b09-c11775cb07f0"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3161), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019ece85-30ad-7412-88c2-a81a44c998fc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3157), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7bb6-b751-b4e58df5cda3"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3168), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3164), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7696-8fe3-f5edf1a1c02b"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3189), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3171), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7f17-8e7e-1bde323e2985"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3196), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3192), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-71a3-b32d-2eddd8b953ef"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3207), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3204), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-789d-a5a2-6eec2bba22ce"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3213), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3210), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7252-966c-5e85038608e7"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3220), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3216), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-740e-9a2e-afee11b34979"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3226), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3223), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7081-9e10-f63ca5c5833c"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3234), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3230), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7c90-b2bd-f54ca3d55627"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3240), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3237), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7bd4-8dc1-accc6b6a4c6f"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3250), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3243), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7b6f-8155-c0b13fbcd6de"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3257), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3253), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-7289-a14d-090f988ca849"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3263), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3260), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-3268-796e-897a-0657ce3d7014"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3269), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3266), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ece85-30ad-7412-88c2-a81a44c998fc"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3070), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3067), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-30ad-717e-9b67-32b826bcc65c"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3076), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3074), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-30ad-7504-a60f-00a6471bb3cc"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3081), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3079), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(2855), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(2852), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(2861), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(2860), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7743-a256-61730dcbc7a0")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7a6e-9b09-c11775cb07f0")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7bb6-b751-b4e58df5cda3")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7696-8fe3-f5edf1a1c02b")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7f17-8e7e-1bde323e2985")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-71a3-b32d-2eddd8b953ef")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-789d-a5a2-6eec2bba22ce")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7252-966c-5e85038608e7")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-740e-9a2e-afee11b34979")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7081-9e10-f63ca5c5833c")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7c90-b2bd-f54ca3d55627")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7bd4-8dc1-accc6b6a4c6f")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7b6f-8155-c0b13fbcd6de")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-7289-a14d-090f988ca849")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598"),
                            PermissionId = new Guid("019ece85-3268-796e-897a-0657ce3d7014")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            PermissionId = new Guid("019ece85-3268-7743-a256-61730dcbc7a0")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            PermissionId = new Guid("019ece85-3268-7a6e-9b09-c11775cb07f0")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            PermissionId = new Guid("019ece85-3268-7bb6-b751-b4e58df5cda3")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            PermissionId = new Guid("019ece85-3268-789d-a5a2-6eec2bba22ce")
                        },
                        new
                        {
                            RoleId = new Guid("019ece85-30ad-7042-b491-bef0128e8b3e"),
                            PermissionId = new Guid("019ece85-3268-7252-966c-5e85038608e7")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3716), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 3, 41, 36, 232, DateTimeKind.Unspecified).AddTicks(3712), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019ece85-30ad-7ada-94f1-c2844e5ae464"),
                            RoleId = new Guid("019ece85-30ad-76a8-9f2b-7e04a5dcb598")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
