// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625035054_DashboardCode")]
    partial class DashboardCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eed25-b9cc-794c-810b-78aa25c6a3af"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019eed25-b9cb-72a8-bb2e-cde54dc0f0ae"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(6943), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-714e-a4a5-65b7618479d0"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019eed25-b9cb-72a8-bb2e-cde54dc0f0ae"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9430), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-7e77-8537-70d11bbbaeb5"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9441), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-79e1-aa4d-5fdb20386a3a"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9446), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-7dc5-8971-05b0664f7cbc"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9451), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-778e-ae06-f9818fbca912"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9462), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-7443-97b5-a1cb8fff24f5"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9466), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-74f9-b319-7cb58f050238"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9470), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cc-7638-a730-8199fc197a58"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9474), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-7208-831d-00b76a0ca679"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9527), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-7b05-9a0d-d4a3576e908a"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9531), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-773f-b37b-65f8db97edf2"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9536), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-77c2-afef-01e092e22359"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9540), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-72ee-a00d-dc1e3f02fae6"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9544), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-7175-a2d2-1b8f0b06791a"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9548), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-7007-bb65-1eca5d5baa4b"),
                            Code = "media.create_category",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Create Category",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9553), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cd-731f-bdc6-037a645e66c2"),
                            Code = "media.media.update_category",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Update Category",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9557), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019efce4-bbe7-72cc-b9f3-148451491a87"),
                            Code = "admin.dashboard",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Admin Dashboard",
                            PermissionGroupId = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(9563), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eed25-b9cb-72a8-bb2e-cde54dc0f0ae"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(4668), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cb-74ad-bd0b-dcc44f4d0e63"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(5779), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cb-7238-aad7-74e3c7d0aa5d"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 544, DateTimeKind.Unspecified).AddTicks(5838), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 542, DateTimeKind.Unspecified).AddTicks(7746), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 543, DateTimeKind.Unspecified).AddTicks(3588), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-794c-810b-78aa25c6a3af")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-714e-a4a5-65b7618479d0")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-7e77-8537-70d11bbbaeb5")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-79e1-aa4d-5fdb20386a3a")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-7dc5-8971-05b0664f7cbc")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-778e-ae06-f9818fbca912")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-7443-97b5-a1cb8fff24f5")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-74f9-b319-7cb58f050238")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cc-7638-a730-8199fc197a58")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-7208-831d-00b76a0ca679")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-7b05-9a0d-d4a3576e908a")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-773f-b37b-65f8db97edf2")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-77c2-afef-01e092e22359")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-72ee-a00d-dc1e3f02fae6")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-7175-a2d2-1b8f0b06791a")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-7007-bb65-1eca5d5baa4b")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019eed25-b9cd-731f-bdc6-037a645e66c2")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112"),
                            PermissionId = new Guid("019efce4-bbe7-72cc-b9f3-148451491a87")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            PermissionId = new Guid("019eed25-b9cc-794c-810b-78aa25c6a3af")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            PermissionId = new Guid("019eed25-b9cc-714e-a4a5-65b7618479d0")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            PermissionId = new Guid("019eed25-b9cc-7e77-8537-70d11bbbaeb5")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            PermissionId = new Guid("019eed25-b9cc-7443-97b5-a1cb8fff24f5")
                        },
                        new
                        {
                            RoleId = new Guid("019eed25-b9cb-75a5-b4dc-ed6e00d0b41a"),
                            PermissionId = new Guid("019eed25-b9cc-74f9-b319-7cb58f050238")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_first_login");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            IsFirstLogin = false,
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 3, 50, 53, 546, DateTimeKind.Unspecified).AddTicks(3227), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019eed25-b9cc-7b05-b21b-f4c3f68c9d06"),
                            RoleId = new Guid("019eed25-b9ba-7c95-bff5-2f166b4e0112")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("has_children");

                    b.Property<Guid?>("ReferenceCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_comment_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<long>("Progress")
                        .HasColumnType("bigint")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("UserId", "MediaId")
                        .IsUnique();

                    b.ToTable("media_histories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<int>("ReactionType")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MediaId")
                        .IsUnique();

                    b.ToTable("media_reactions");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MovieRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rating_count");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "UserId")
                        .IsUnique();

                    b.ToTable("movie_ratings");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsNotice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_notice");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SubscriberId");

                    b.HasIndex("ChannelId", "SubscriberId")
                        .HasFilter("\"is_notice\" = true");

                    b.HasIndex("SubscriberId", "ChannelId")
                        .IsUnique();

                    b.ToTable("subscribers");
                });

            modelBuilder.Entity("chillhub.Entities.Media.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Id");

                    b.ToTable("user_notifications");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Comment", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaHistory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId");

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Subscriber", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
