// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616051919_AlterMedia2")]
    partial class AlterMedia2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ecede-a45b-74cb-8f13-dc716549d2e8"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6538), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019ecede-a234-7a57-9326-10c4887fd084"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6497), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7c82-86f9-2b6215320d01"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6550), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019ecede-a234-7a57-9326-10c4887fd084"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6545), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7cc3-aa43-f788774c3782"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6558), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6553), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7873-a253-5c0f2d8aacd4"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6564), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6560), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7a9f-9e9b-53c9d3bec744"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6570), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6567), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7305-b2d6-09fd9c114140"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6579), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7a8c-8cb6-593e8d471561"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6604), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6601), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7769-ad76-8543f6ec20f2"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6610), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6607), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-760f-8d16-be2c03c7af61"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6617), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6613), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7f5f-b56c-ae00c9389fa4"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6625), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6621), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7f3a-8118-8eca2b14240f"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6631), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6628), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7c1f-b68c-d5f5e17c0816"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6637), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6634), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7e09-b816-103e78db06bd"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6643), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6640), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7240-beb9-7f1734b0ad07"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6654), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6646), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a45b-7bcf-8965-9b4be2756962"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6661), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6657), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ecede-a234-7a57-9326-10c4887fd084"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6465), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6462), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a234-70e9-aeee-42e6f84927c2"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6472), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6469), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a234-7244-bbfa-e154d0e64613"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6477), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6475), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6248), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6246), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6255), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(6254), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-74cb-8f13-dc716549d2e8")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7c82-86f9-2b6215320d01")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7cc3-aa43-f788774c3782")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7873-a253-5c0f2d8aacd4")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7a9f-9e9b-53c9d3bec744")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7305-b2d6-09fd9c114140")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7a8c-8cb6-593e8d471561")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7769-ad76-8543f6ec20f2")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-760f-8d16-be2c03c7af61")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7f5f-b56c-ae00c9389fa4")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7f3a-8118-8eca2b14240f")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7c1f-b68c-d5f5e17c0816")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7e09-b816-103e78db06bd")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7240-beb9-7f1734b0ad07")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba"),
                            PermissionId = new Guid("019ecede-a45b-7bcf-8965-9b4be2756962")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            PermissionId = new Guid("019ecede-a45b-74cb-8f13-dc716549d2e8")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            PermissionId = new Guid("019ecede-a45b-7c82-86f9-2b6215320d01")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            PermissionId = new Guid("019ecede-a45b-7cc3-aa43-f788774c3782")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            PermissionId = new Guid("019ecede-a45b-7a8c-8cb6-593e8d471561")
                        },
                        new
                        {
                            RoleId = new Guid("019ecede-a234-7db3-bf6d-878a250b1cfb"),
                            PermissionId = new Guid("019ecede-a45b-7769-ad76-8543f6ec20f2")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(7067), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 16, 5, 19, 18, 107, DateTimeKind.Unspecified).AddTicks(7062), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019ecede-a234-722a-8629-25510beaa97f"),
                            RoleId = new Guid("019ecede-a234-75f3-8b83-b941d7d7f1ba")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
