// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620102732_MediaHistory")]
    partial class MediaHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ee492-4553-70e6-b912-0e9a9a316e83"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5526), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019ee492-437a-7b6d-acdb-bc80f47e3804"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5476), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7b29-b5b6-6ad8ce8864e3"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5537), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019ee492-437a-7b6d-acdb-bc80f47e3804"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5533), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-77d3-956b-59fed414e80e"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5543), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5539), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7459-b7af-758c231df61b"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5564), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5546), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7cfb-8990-25ff62fd65df"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5571), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5568), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7c8f-accf-2120e5119604"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5582), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5579), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-745a-a5c0-a946c7dd99cc"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5588), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5585), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7734-90f0-76227c22c772"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5594), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5591), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-75bb-bcec-2544be5bcccf"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5600), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5597), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-765f-9c12-0508f1c17c93"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5608), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5604), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7b67-a02d-b79aae970c39"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5614), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5610), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7fbf-a579-bdcee8437dfd"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5625), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5617), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7fc7-a292-f3493138756d"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5631), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5627), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7f33-8fcb-134d97443ccd"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5636), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5633), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7c0c-90ef-27cbf610a822"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5642), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5639), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-7ef4-91ca-367ab189972a"),
                            Code = "media.create_category",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5648), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Create Category",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5645), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-4553-73b0-a5cb-72b82b9b250e"),
                            Code = "media.media.update_category",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5654), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Update Category",
                            PermissionGroupId = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5651), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ee492-437a-7b6d-acdb-bc80f47e3804"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5450), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5447), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-437a-7e75-92c7-8dfe993b92db"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5455), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5453), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-437a-722b-a863-4004f5dd63a4"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5460), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5458), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5233), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5231), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5240), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(5239), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-70e6-b912-0e9a9a316e83")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7b29-b5b6-6ad8ce8864e3")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-77d3-956b-59fed414e80e")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7459-b7af-758c231df61b")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7cfb-8990-25ff62fd65df")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7c8f-accf-2120e5119604")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-745a-a5c0-a946c7dd99cc")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7734-90f0-76227c22c772")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-75bb-bcec-2544be5bcccf")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-765f-9c12-0508f1c17c93")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7b67-a02d-b79aae970c39")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7fbf-a579-bdcee8437dfd")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7fc7-a292-f3493138756d")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7f33-8fcb-134d97443ccd")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7c0c-90ef-27cbf610a822")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-7ef4-91ca-367ab189972a")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357"),
                            PermissionId = new Guid("019ee492-4553-73b0-a5cb-72b82b9b250e")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            PermissionId = new Guid("019ee492-4553-70e6-b912-0e9a9a316e83")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            PermissionId = new Guid("019ee492-4553-7b29-b5b6-6ad8ce8864e3")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            PermissionId = new Guid("019ee492-4553-77d3-956b-59fed414e80e")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            PermissionId = new Guid("019ee492-4553-745a-a5c0-a946c7dd99cc")
                        },
                        new
                        {
                            RoleId = new Guid("019ee492-437a-7b4c-8d51-9259bc6a23a8"),
                            PermissionId = new Guid("019ee492-4553-7734-90f0-76227c22c772")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_first_login");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(6079), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            IsFirstLogin = false,
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 20, 10, 27, 31, 795, DateTimeKind.Unspecified).AddTicks(6075), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019ee492-437a-72f2-b5aa-d52c8d85e2e1"),
                            RoleId = new Guid("019ee492-437a-798d-b2eb-716564ab3357")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<long>("Progress")
                        .HasColumnType("bigint")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("UserId");

                    b.ToTable("media_histories");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaHistory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId");

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
