// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610181750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-74dd-8690-16b4a40c5197"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(507), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019eb2c1-3d08-705f-9139-d4d227b3dec1"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(462), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7ccf-a0d6-d344eb18e813"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(517), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019eb2c1-3d08-705f-9139-d4d227b3dec1"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(513), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-746f-9b2b-50cf1f8fc239"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(524), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(520), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-78db-a485-81366fde8682"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(530), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(527), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-777e-9acb-478ff84fae6e"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(536), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(532), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7656-9ff1-678df50c79ce"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(545), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(542), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7b98-85c1-6e279ac7cfbb"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(551), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(548), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7009-8dc3-dc7e9a182b2e"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(572), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(554), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7e5b-aa41-c99a4b96912c"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(578), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(575), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7281-a7bb-ae874c027be8"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(586), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(583), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7aae-b777-ed227bb48f43"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(592), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(589), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7c38-aa58-21bdad397eb3"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(595), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7b54-af8a-3caadb61587c"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(603), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(600), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-7316-8881-ffe3b855b8c3"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(609), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(606), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3eb3-786b-a576-8952818fc44a"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(615), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(612), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-705f-9139-d4d227b3dec1"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(433), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(431), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-7781-b41b-9018dbcb8746"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(439), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(437), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-7223-b8b8-716fd37cc0d0"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(444), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(442), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(207), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(203), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(214), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(213), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-74dd-8690-16b4a40c5197")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7ccf-a0d6-d344eb18e813")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-746f-9b2b-50cf1f8fc239")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-78db-a485-81366fde8682")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-777e-9acb-478ff84fae6e")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7656-9ff1-678df50c79ce")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7b98-85c1-6e279ac7cfbb")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7009-8dc3-dc7e9a182b2e")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7e5b-aa41-c99a4b96912c")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7281-a7bb-ae874c027be8")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7aae-b777-ed227bb48f43")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7c38-aa58-21bdad397eb3")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7b54-af8a-3caadb61587c")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-7316-8881-ffe3b855b8c3")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2"),
                            PermissionId = new Guid("019eb2c1-3eb3-786b-a576-8952818fc44a")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            PermissionId = new Guid("019eb2c1-3eb3-74dd-8690-16b4a40c5197")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            PermissionId = new Guid("019eb2c1-3eb3-7ccf-a0d6-d344eb18e813")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            PermissionId = new Guid("019eb2c1-3eb3-746f-9b2b-50cf1f8fc239")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            PermissionId = new Guid("019eb2c1-3eb3-7b98-85c1-6e279ac7cfbb")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c1-3d08-7559-b203-dbfcf9bfe2c1"),
                            PermissionId = new Guid("019eb2c1-3eb3-7009-8dc3-dc7e9a182b2e")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(1019), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 17, 49, 491, DateTimeKind.Unspecified).AddTicks(1016), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019eb2c1-3d08-74f8-9a12-2b806f3d4b57"),
                            RoleId = new Guid("019eb2c1-3d08-7dfd-b826-f3a006a76ab2")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
