// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610182125_Dashboard")]
    partial class Dashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-78d6-ba34-2e99f697ffdf"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7628), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019eb2c4-8808-7abe-b09a-ce89d9fc0ac9"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7585), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7fb7-a86a-3e7c27d5a740"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7639), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019eb2c4-8808-7abe-b09a-ce89d9fc0ac9"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7635), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7c67-a6af-13feb44ab201"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7646), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7642), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7958-9bb4-d052d3532b6d"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7652), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7649), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7eea-8c6a-a308e4e72a71"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7673), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7655), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-74ff-a8ca-2952c4f011d7"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7685), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7682), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7882-a28d-33bc71958934"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7691), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7688), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7a2d-9858-bedc226816da"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7697), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7694), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-729b-b8cc-e6371926275d"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7703), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7700), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7869-b09c-3a9e40163ec5"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7710), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7707), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7053-b5a5-8b793b78b7ea"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7716), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7713), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7c95-aa96-40d46f2e8899"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7722), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7719), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-7945-959b-bcb905ed6d56"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7733), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7725), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-79c8-afba-21e149cfc195"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7740), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7736), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-89b2-772e-8429-026f51558c58"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7745), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7742), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c4-8808-7abe-b09a-ce89d9fc0ac9"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7557), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7555), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-8808-7f34-bb5b-519f9694b5a2"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7563), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7561), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-8808-713e-a003-79fffee5235c"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7567), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7566), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7339), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7337), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7345), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(7344), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-78d6-ba34-2e99f697ffdf")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7fb7-a86a-3e7c27d5a740")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7c67-a6af-13feb44ab201")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7958-9bb4-d052d3532b6d")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7eea-8c6a-a308e4e72a71")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-74ff-a8ca-2952c4f011d7")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7882-a28d-33bc71958934")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7a2d-9858-bedc226816da")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-729b-b8cc-e6371926275d")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7869-b09c-3a9e40163ec5")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7053-b5a5-8b793b78b7ea")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7c95-aa96-40d46f2e8899")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-7945-959b-bcb905ed6d56")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-79c8-afba-21e149cfc195")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a"),
                            PermissionId = new Guid("019eb2c4-89b2-772e-8429-026f51558c58")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            PermissionId = new Guid("019eb2c4-89b2-78d6-ba34-2e99f697ffdf")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            PermissionId = new Guid("019eb2c4-89b2-7fb7-a86a-3e7c27d5a740")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            PermissionId = new Guid("019eb2c4-89b2-7c67-a6af-13feb44ab201")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            PermissionId = new Guid("019eb2c4-89b2-7882-a28d-33bc71958934")
                        },
                        new
                        {
                            RoleId = new Guid("019eb2c4-8808-7446-b3aa-7cb1f0661715"),
                            PermissionId = new Guid("019eb2c4-89b2-7a2d-9858-bedc226816da")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(8125), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 18, 21, 25, 298, DateTimeKind.Unspecified).AddTicks(8120), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019eb2c4-8808-7602-91b5-fdf7caf2b8a9"),
                            RoleId = new Guid("019eb2c4-8808-7d24-9999-758c0d5a976a")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
