// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618151851_FolderId")]
    partial class FolderId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019edb50-4285-7d91-88db-ea77cf84c88d"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7673), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019edb50-40c7-7109-9bbb-96387b8c213a"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7626), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7497-823d-2cc04576f88b"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7684), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019edb50-40c7-7109-9bbb-96387b8c213a"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7679), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7c4a-8752-463a87cec46b"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7690), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7687), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-791b-8c98-940a39daf07e"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7696), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7693), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7e79-8991-bbbc0de4bc0a"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7715), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7699), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7e79-be3a-281072f32552"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7727), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7724), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-71c1-ad15-1bf2b42e0325"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7733), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7730), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7edf-904b-d406f3ae5b9e"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7739), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7736), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7a88-9e7f-e7ed9df1f997"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7745), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7742), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7a05-a769-248efecfea40"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7752), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7749), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7bac-b441-e6bb5b2be127"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7758), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7755), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7f0c-a635-dc69c4576d0b"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7764), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7761), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-754f-8900-b4be6bc61e6b"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7774), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7766), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7ef0-ad15-2b3ae7e7cc6b"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7780), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7776), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-4285-7633-8e98-abb9736248a9"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7785), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7782), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019edb50-40c7-7109-9bbb-96387b8c213a"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7594), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-40c7-77ef-a98d-c68bcc301ba0"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7603), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7601), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-40c7-7158-a0cd-8b5f26e9fc65"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7608), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7606), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7394), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7391), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7400), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(7399), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7d91-88db-ea77cf84c88d")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7497-823d-2cc04576f88b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7c4a-8752-463a87cec46b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-791b-8c98-940a39daf07e")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7e79-8991-bbbc0de4bc0a")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7e79-be3a-281072f32552")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-71c1-ad15-1bf2b42e0325")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7edf-904b-d406f3ae5b9e")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7a88-9e7f-e7ed9df1f997")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7a05-a769-248efecfea40")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7bac-b441-e6bb5b2be127")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7f0c-a635-dc69c4576d0b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-754f-8900-b4be6bc61e6b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7ef0-ad15-2b3ae7e7cc6b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159"),
                            PermissionId = new Guid("019edb50-4285-7633-8e98-abb9736248a9")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            PermissionId = new Guid("019edb50-4285-7d91-88db-ea77cf84c88d")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            PermissionId = new Guid("019edb50-4285-7497-823d-2cc04576f88b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            PermissionId = new Guid("019edb50-4285-7c4a-8752-463a87cec46b")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            PermissionId = new Guid("019edb50-4285-71c1-ad15-1bf2b42e0325")
                        },
                        new
                        {
                            RoleId = new Guid("019edb50-40c7-7150-b1ea-641086199b58"),
                            PermissionId = new Guid("019edb50-4285-7edf-904b-d406f3ae5b9e")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(8267), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 15, 18, 50, 757, DateTimeKind.Unspecified).AddTicks(8262), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019edb50-40c7-79d8-835d-dae47469b4f5"),
                            RoleId = new Guid("019edb50-40c7-7d5e-9a20-1ff76a9a7159")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
