// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523060354_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019e536e-d69a-765f-b3b9-effc4f028dc0"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6546), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019e536e-d4c0-7524-939f-1e1ff4b0cbba"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6498), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7a1c-889e-96d15911bb8e"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6555), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019e536e-d4c0-7524-939f-1e1ff4b0cbba"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6551), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7fcd-b34e-da6584e58bf8"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6563), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6558), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7dff-a555-2794489e53d7"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6570), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6566), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-751b-bee8-b1d05cc80b26"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6576), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6572), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7691-895e-f1001d0e3387"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6602), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6584), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7d0e-8795-31cf3c3d7683"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6608), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6605), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7e12-bc0d-65a1c0f3cbe5"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6614), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6611), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-712a-9950-670784a5c901"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6621), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6617), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7b9a-827a-b259bc3fee34"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6629), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6626), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-751e-ad70-f47a2ea7b5ab"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6636), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6632), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7962-94ce-155c394d71ce"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6643), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6639), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7f86-bc71-fb4ef40a52cf"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6649), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6646), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7618-a780-0223df6f973d"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6660), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6652), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d69a-7fd4-92c5-5a95c8df7c0a"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6667), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6664), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019e536e-d4c0-7524-939f-1e1ff4b0cbba"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6466), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6463), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d4c0-753a-8840-d6cb51f38090"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6471), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6470), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d4c0-73f0-8efa-3decc75e8521"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6477), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6475), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6178), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6176), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6185), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(6184), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-765f-b3b9-effc4f028dc0")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7a1c-889e-96d15911bb8e")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7fcd-b34e-da6584e58bf8")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7dff-a555-2794489e53d7")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-751b-bee8-b1d05cc80b26")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7691-895e-f1001d0e3387")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7d0e-8795-31cf3c3d7683")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7e12-bc0d-65a1c0f3cbe5")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-712a-9950-670784a5c901")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7b9a-827a-b259bc3fee34")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-751e-ad70-f47a2ea7b5ab")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7962-94ce-155c394d71ce")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7f86-bc71-fb4ef40a52cf")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7618-a780-0223df6f973d")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2"),
                            PermissionId = new Guid("019e536e-d69a-7fd4-92c5-5a95c8df7c0a")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            PermissionId = new Guid("019e536e-d69a-765f-b3b9-effc4f028dc0")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            PermissionId = new Guid("019e536e-d69a-7a1c-889e-96d15911bb8e")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            PermissionId = new Guid("019e536e-d69a-7fcd-b34e-da6584e58bf8")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            PermissionId = new Guid("019e536e-d69a-7d0e-8795-31cf3c3d7683")
                        },
                        new
                        {
                            RoleId = new Guid("019e536e-d4c0-7123-9344-5ae57959cf47"),
                            PermissionId = new Guid("019e536e-d69a-7e12-bc0d-65a1c0f3cbe5")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(7132), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 6, 3, 53, 370, DateTimeKind.Unspecified).AddTicks(7129), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019e536e-d4c0-7586-a234-9f4ec68d0f48"),
                            RoleId = new Guid("019e536e-d4c0-72ba-b860-6d3fda8b61d2")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
