// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chillhub.Contexts;

#nullable disable

namespace chillhub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615002318_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ec8a9-4884-79cd-9c89-84f847dc6e18"),
                            Code = "auth.login",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5365), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Login",
                            PermissionGroupId = new Guid("019ec8a9-46be-78b2-9a4b-26385831c47c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5318), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-78de-b473-fae27dea0e93"),
                            Code = "auth.logout",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5376), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Logout",
                            PermissionGroupId = new Guid("019ec8a9-46be-78b2-9a4b-26385831c47c"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5372), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-73d9-9082-aca578be0435"),
                            Code = "user.read",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5397), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "View User's Details",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5379), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7e30-84ef-4e42718943a5"),
                            Code = "user.create",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5404), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Add New User",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5400), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7327-925e-bd09b30c3085"),
                            Code = "user.update",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5410), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Update User's Details",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5406), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7f3b-806f-4130795acf66"),
                            Code = "user.delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5420), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Delete User",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5417), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7150-9bd8-3dc984224d11"),
                            Code = "user.view_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5426), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "View Users",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5423), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7f82-8348-3215c4045e1f"),
                            Code = "auth.view_session",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5432), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Get Session",
                            PermissionGroupId = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5429), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-75b1-bfa1-7e41ccdbc87e"),
                            Code = "rbac.save_permission_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5438), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Save Permission Group",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5434), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-729f-8b21-7c417ced5226"),
                            Code = "rbac.search_permission_groups",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5445), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Search Permission Groups",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5442), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7eea-9c6c-3dd988405222"),
                            Code = "rbac.save_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5455), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Save Role",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5448), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-7815-be34-e6e6a88dd275"),
                            Code = "rbac.search_roles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5462), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Search Roles",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5458), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-730f-adcc-73d7e98cd661"),
                            Code = "rbac.save_permission",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5468), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Save Permissions",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5464), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-70e2-b433-fbf70e7c46bb"),
                            Code = "rbac.search_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5473), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Search Permissions",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5470), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-4884-75e6-8dbd-0cb45c575260"),
                            Code = "rbac.assign_role",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5479), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Assign Roles",
                            PermissionGroupId = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5476), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ec8a9-46be-78b2-9a4b-26385831c47c"),
                            Code = "auth_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5290), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "Auth",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5286), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-46be-7f68-862b-5049f8fd3888"),
                            Code = "user_group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5295), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "User",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5293), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-46be-7513-aab7-8d669d4101c3"),
                            Code = "rbac_group.admin",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5300), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "RBAC Management",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5298), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5027), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5024), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5035), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Name = "user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5033), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-79cd-9c89-84f847dc6e18")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-78de-b473-fae27dea0e93")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-73d9-9082-aca578be0435")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7e30-84ef-4e42718943a5")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7327-925e-bd09b30c3085")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7f3b-806f-4130795acf66")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7150-9bd8-3dc984224d11")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7f82-8348-3215c4045e1f")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-75b1-bfa1-7e41ccdbc87e")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-729f-8b21-7c417ced5226")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7eea-9c6c-3dd988405222")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-7815-be34-e6e6a88dd275")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-730f-adcc-73d7e98cd661")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-70e2-b433-fbf70e7c46bb")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899"),
                            PermissionId = new Guid("019ec8a9-4884-75e6-8dbd-0cb45c575260")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            PermissionId = new Guid("019ec8a9-4884-79cd-9c89-84f847dc6e18")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            PermissionId = new Guid("019ec8a9-4884-78de-b473-fae27dea0e93")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            PermissionId = new Guid("019ec8a9-4884-73d9-9082-aca578be0435")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            PermissionId = new Guid("019ec8a9-4884-7150-9bd8-3dc984224d11")
                        },
                        new
                        {
                            RoleId = new Guid("019ec8a9-46be-7cbd-ab33-260ffc78dd0c"),
                            PermissionId = new Guid("019ec8a9-4884-7f82-8348-3215c4045e1f")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<int>("Lang")
                        .HasColumnType("integer")
                        .HasColumnName("lang");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5880), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            Email = "admin@chillhub.id.vn",
                            FullName = "admin",
                            Lang = 0,
                            Password = "AQAAAAIAACcQAAAAEJL3PEfuwNrQOTsclnmWeXII/9NzpgehrbMF6gOzBfg4BjsiMVqewvfP5/LtaNKj4w==",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 23, 17, 892, DateTimeKind.Unspecified).AddTicks(5876), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019ec8a9-46be-7ac6-9ee7-5795c1e53cb4"),
                            RoleId = new Guid("019ec8a9-46be-7455-9c77-7b427c340899")
                        });
                });

            modelBuilder.Entity("chillhub.Entities.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediasCount")
                        .HasColumnType("integer")
                        .HasColumnName("medias_count");

                    b.Property<int>("PermissionGroupsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permission_groups_count");

                    b.Property<int>("PermissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_count");

                    b.Property<int>("RolesCount")
                        .HasColumnType("integer")
                        .HasColumnName("roles_count");

                    b.Property<int>("UsersCount")
                        .HasColumnType("integer")
                        .HasColumnName("users_count");

                    b.HasKey("Id");

                    b.ToTable("dashboard");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dislike_count");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<int>("MediaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("media_status");

                    b.Property<float?>("OverallRating")
                        .HasColumnType("real")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("medias");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("media_categories");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.HasOne("chillhub.Entities.Auth.User", "User")
                        .WithMany("Medias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("chillhub.Entities.Media.MediaCategory", b =>
                {
                    b.HasOne("chillhub.Entities.Media.Category", "Category")
                        .WithMany("MediaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("chillhub.Entities.Media.Media", "Media")
                        .WithMany("MediaCategories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Auth.User", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Category", b =>
                {
                    b.Navigation("MediaCategories");
                });

            modelBuilder.Entity("chillhub.Entities.Media.Media", b =>
                {
                    b.Navigation("MediaCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
